### PR TITLE
from _pgBackRest_ to pgBackRest

### PR DESCRIPTION
**Pull request by bradnoble**
Find and replace on all instances in the pgBackRest dir.

### CODE REVIEW

**Comment by pgstef** [comment]
`temp_pgbackrest` may be removed since we've merged pgbackrest-docs into advocacy_docs (which became the docs source when pgbackrest-docs was deleted).

**Comment by bradnoble** [comment]
@pgstef where are you seeing `temp_pgbackrest`?

**Comment by pgstef** [comment]
https://github.com/EnterpriseDB/docs/tree/bn-remove-italics-around-pgBackRest/temp_pgbackrest

I've seen tome typos while reading your corrections. I'll try to commit a small fix + delete this old directory

**Comment by bradnoble** [comment]
Great, thanks.

**Review by pgstef — APPROVED** [review]
Pushed 7454cd2 to fix some typos and consistency issues.
That's good for me now.

**Pull request merged**
