### PR TITLE
Attempt to change Advanced Search

### PR DESCRIPTION
**Pull request by drothery-edb**
Attempting to change Advanced Search label. See solution option 2 in https://github.com/EnterpriseDB/docs/issues/1874

### CODE REVIEW

**Comment by drothery-edb** [comment]
@jericson-edb , @josh-heyer, I don't know how to test this.

**Comment by josh-heyer** [comment]
Draft deploy did show your changes, just missed a few spots. See commit

**Comment by drothery-edb** [comment]
Thanks @josh-heyer. Can you or @jericson-edb approve the PR?

**Review by jericson-edb — APPROVED** [review]
Looks good to me.

Addresses: #1874

**Pull request merged**
