### PR TITLE
Edits to BigAnimal release notes in PR5127

### PR DESCRIPTION
**Pull request by ebgitelman**

### CODE REVIEW

**Comment by ebgitelman** [comment]
@nidhibhammar Our standard is to include this text after the title (for example):

Released: 09 Nov 2023

However, I'm not sure whether that applies to BigAnimal. Is there a specific date that makes sense to mention? Or is "September release" (for example) sufficient? 

@josh-heyer Please weigh in with any thoughts.

**Comment by nidhibhammar** [comment]
@ebgitelman, Yes, I agree. For BigAnimal, they go by a monthly release cycle, and they don't have specific dates. We have added the release notes for the first time in BigAnimal, and the request came in through PM. They asked me not to add the release date as of now hence not added.

**Comment by ebgitelman** [comment]
@nidhibhammar Okay, then my review of your PR is complete and ready to be merged.

**Review by nidhibhammar — APPROVED** [review]
LGTM

**Pull request merged**
