### PR TITLE
Add edb_sqlpatch information on minor version up page for EPAS 15 manual

### PR DESCRIPTION
**Pull request by yuki-tei**
Hi team,
Greetings.

We've found that your minor upgrade page lacks the information about edb_sqlpatch description, which is needed for example v15.4.

## What Changed?
Add edb_sqlpatch command sample and link to its manual page at bottom.

### CODE REVIEW

**Review by djw-m — COMMENTED** [review]
This is very unclear. The instructions don't instruct you to run edb_sqlpatch, but you are supposed to take action based on it's result?

Does any of the preceding steps run edb_sqlpatch automatically? If not, shouldn't there be a patching step?

Happy to discuss.

**Comment by yuki-tei** [comment]
Hi,
Thanks for your quick reply. Apologies for my description might be confusing.

The most important point for this page is that edb_sqlpatch doesn't exist till 15.4.
So the newbee for EDB might look into this minor update instruction page and doesn't aware of the need to apply edb_sqlpatch.

So the idea was first to at least give a link for edb_sqlpatch on this page.
However, even do so, especially the new customers might not know in which case they need edb_sqlpatch post minor release, one idea as you see is to decide by edb_sqlpatch's command result itself. If you have any other ideas, please tell us.

Thanks for your kind advice.
Regards,
Yuki Tei

**Comment by djw-m** [comment]
So, these instructions should read...


!!! 
    
If on version 15.4 or later, you should run `edb_sqlpatch`

If the command responds that it has a number of patches needing to be applied like so:

```console
* database edb
0 patches were previously applied to this database.
58 patches need to be applied to this database.
```

Then it will be necessary to execute edb_sqlpatch to patch the system catalog. Run:

```shell
edb_sqlpatch -af
```

!!!

**Comment by yuki-tei** [comment]
Hi,

Thanks for your quick review and proofreading. 
We believe that makes sense and would be a great help to many customers.
Appreciates to your continuous help.

Kind Regards,
Yuki Tei

**Comment by djw-m** [comment]
@nidhibhammar This change will need back-porting to refer to 11.21.32, 12.16.20, 13.12.17 and 14.9.0 if we merge it.

**Review by nidhibhammar — APPROVED** [review]
LGTM. I agree with back-porting.

**Pull request merged**
