### PR TITLE
add content for BDR 3.7 per issue #1348

### LINKED ISSUE #1348: Feedback on /bdr/3.6/index.mdx
The next major version of BDR is released for GA on Tuesday May 18. 
It would be ideal to have this page for BDR v3.7 **published by May 14** and no later than May 17. 
BDR 3.6 remains the stable version, so both 3.6 and 3.7 doc pages need to be available. 
Reminder: there is a link to the product documentation on the 2Q portal and it would be sensible to follow the highlighting approach done on the existing 3.6 page.
The [attached](https://docs.google.com/document/d/1TH4upGazv6DTTu73A_z7nlWBUssioUZ_k3wFJEqhCnw/edit?usp=sharing) google doc has the update 3.7 content.

### PR DESCRIPTION
**Pull request by josh-heyer**
## What Changed?

Adds a stub page for BDR 3.7 per John Dalton's request. Fixes #1348 

THIS SHOULD NOT BE MERGED UNTIL May 14th!

## Checklist

Please check all boxes that apply (`[ ]` is unchecked, `[x]` is checked)

**Content**
- [x] This PR adds new content
- [ ] This PR changes existing content
- [ ] This PR removes existing content

### CODE REVIEW

**Comment by daltjoh** [comment]
@josh-heyer I'm happy to look at something in a test/staging environment if you can send me a link

**Comment by josh-heyer** [comment]
Here you go, @daltjoh : https://zen-clarke-09b685.netlify.app/docs/bdr/latest/

**Comment by daltjoh** [comment]
Hey @josh-heyer thanks for the link. Here's my feedback:
1. In the topmost section of text, we lost the paragraph breaks. For readability should be 4 paragraphs. (see the [doc](https://docs.google.com/document/d/1TH4upGazv6DTTu73A_z7nlWBUssioUZ_k3wFJEqhCnw/edit#))
2. In the BDR Enterprise section, after the feature list bullets and before the red note identifying exceptions, there looks to be a paragraph carried over from the 3.6 text. Specifically: "BDR Enterprise requires EDB Postgres Extended v11 (formerly known as 2ndQuadrant Postgres) which is SQL and on-disk compatible with PostgreSQL."
3. In the BDR Enterprise section the use of _[extended]_ appears awkward as a notational mark for identifying the feature exceptions. If the double asterisk notation for the BDR Enterprise feature support exceptions can't work due to markdown restrictions, is there some other non letter character that can be used? A single asterisk would be fine, or even _[*]_ Perhaps Matt or Brad have ideas?

**Comment by daltjoh** [comment]
@josh-heyer Latest updates look good to go. Approved to deploy to production. Thanks!

**Comment by josh-heyer** [comment]
Thoughts on switching to a single asterisk for the footnote / "extended" indicator, @daltjoh? I donno, the double asterisk seems a bit off to me, seems to imply a 2nd footnote where no first one exists (hence my initial substitution of a keyword - avoid implying "footnote" at all). 

Ex:

single-asterisk indicator

Bit of internal feedback I got suggested a slight preference for the single asterisk over both double and keyword.

**Comment by daltjoh** [comment]
A single asterisk works for me.

**Comment by josh-heyer** [comment]
Ok; I'll merge this tomorrow and release to production by Friday.

**Comment by daltjoh** [comment]
Awesome! Ship it!

**Review by jericson-edb — APPROVED** [review]
LGTM

**Pull request merged**
