### PR TITLE
max_replication_slot  and parallel apply

### PR DESCRIPTION
**Pull request by ashutosh-bapat**
Fix the paragraph explaining max_replication_slot setting for parallel apply

**Content**

- [ ] This PR adds new content
- [x] This PR changes existing content
- [ ] This PR removes existing content
- [ ] This PR is for a release, please add this tag:

### CODE REVIEW

**Review by drothery-edb — DISMISSED** [review]

**Comment by drothery-edb** [comment]
@ashutosh-bapat , does this need a technical review from @pavanvd before merging? Should the change be applied to 3.7 also?

**Comment by ashutosh-bapat** [comment]
> @ashutosh-bapat , does this need a technical review from @pavanvd before merging? Should the change be applied to 3.7 also?

Yes to both.

**Comment by pavanvd** [comment]
I think we should make couple of things clear, so that users can make the right choice:
- changing max_replication_slots requires server restart
- the desired value depends on the size of the cluster, including any future node additions and future increase in the number of parallel writers
- cost associated with having a higher value than strictly needed (low, medium, high etc)

Since the parameter change requires a server restart, if the user starts with a strict value (say 4 for a 4 node cluster) and later wants to add more nodes to the cluster, it will require them to change the value of existing nodes first, restart those nodes and then only be able to add more nodes. So they might prefer to configure a slightly higher value to begin with, assuming the cost is low (which I think is the case)

Also, we should add a line about how Postgres derives max origins from max_replication_slots (there is no separate GUC) and hence it's necessary to increase max_replication_slots with parallel writers even though writers themselves don't consume replication slots (they consume origins)

**Comment by drothery-edb** [comment]
@ashutosh-bapat once you incorporate @pavanvd 's comments, we can copy the final content to 3.7. In the meantime I copied the draft to the new source location of the BDR docs. The old location will be removed soon.

**Comment by djw-m** [comment]
@ashutosh-bapat are these changes still relevant and can we get an update on the content to match @pavanvd 's comments. Thanks.

**Comment by ashutosh-bapat** [comment]
> @ashutosh-bapat are these changes still relevant and can we get an update on the content to match @pavanvd 's comments. Thanks.

@djw-m I believe the changes are still relevant. I never got time to look at Pavan's comments. But I am not working on those anymore.

**Comment by djw-m** [comment]
Cherry picked in https://github.com/EnterpriseDB/docs/pull/4662 for changes to live on. This PR is now closed.

**Pull request closed without merging**
