### PR TITLE
doc(UPM-2321): Document CNP metrics exposed by UPM

### PR DESCRIPTION
**Pull request by ringerc**
## What Changed?

EDB Cloud product documentation: Add a list of metrics exposed by EDB Cloud to the customer Azure Log Workspace. Include details on metrics and log entry structure, custom tables exposed, and some guidance on how to get started querying them.

## Checklist

**Content**

- [x] This PR adds new content
- [x] This PR changes existing content
- [ ] This PR removes existing content
- [x] This PR is for a release, please add this tag: Upcoming EDB Cloud release

### CODE REVIEW

**Comment by ringerc** [comment]
Note that this documentation change contains a section that is generated by a script. The script is indended to be hosted in the upm-substrate repo. It doesn't seem practical to add the script here and have it re-generate the automatically generated section on every run, so updating it is expected to be part of the UPM release process for now.

Feedback on the docs structure would be welcomed. I'm not sure if it's best to have the generated metrics list in a separate file that contains only the generated content, or if the present approach with a delimited generated section is preferred.

Please keep in mind the EDB Cloud name consideration.

**Review by SebastienSyd — APPROVED** [review]
Good job @ringerc. LGTM

**Comment by ringerc** [comment]
Goody, conflict with mass rename. Will fix.

**Comment by ringerc** [comment]
The mass rename was not in a separate commit to a bunch of content changes :( so  the rebase will be a bit exciting

**Comment by ringerc** [comment]
Updated, please re-check and merge

**Comment by ringerc** [comment]
Merged, but please kindly check my edits

**Comment by ringerc** [comment]
For reference, the script is on https://enterprisedb.atlassian.net/browse/UPM-2321

**Pull request merged**
