### PR TITLE
Initial updates for efm 4.8.

### PR DESCRIPTION
**Pull request by EFM-Bobby**
There are still some things marked "TODO" and more work needed on the release notes (including a release date).

### CODE REVIEW

**Comment by josh-heyer** [comment]
FYI, when you're about ready to wrap this up let's give @ebgitelman a heads-up - some of this could use a copy-editing pass

**Comment by EFM-Bobby** [comment]
@martinmarques I've marked this as ready for review. I can add you as a reviewer if you want to be in the loop for changes.

**Comment by ebgitelman** [comment]
> @ebgitelman Josh suggested I ask you for a review of this. Sorry the branch is so old -- we originally were going to release 4.8 a while ago but decided to wait. The target date for release now is Nov 14th, so we can't publish these docs yet. But I don't think there will be any other changes from the dev side.

All good. Will work on this today.

**Review by ebgitelman — COMMENTED** [review]
Looks good.

**Comment by EFM-Bobby** [comment]
@ebgitelman Hi, I think I accepted all of the changes you suggested, but because of odd reload behavior I'm wondering if I might have clicked a "Resolve" once without actually getting the changes. I'm not as familiar with doing it this way. If there's any easy way to check please do. Otherwise, I think this is all good if you do, and we should have a more exact date next week to actually release and go live with the docs.

Thank you,
Bobby

**Comment by ebgitelman** [comment]
> Refere

I seem to have found one that wasn't committed so I committed it. If you think it was just one, I apparently found it!

**Comment by EFM-Bobby** [comment]
> > Refere
> 
> I seem to have found one that wasn't committed so I committed it. If you think it was just one, I apparently found it!

Yep, I think there was just the one brain mis-fire. Thanks!

**Comment by EFM-Bobby** [comment]
Hi @ebgitelman I made one commit to change the efm 4.8 release date from yesterday to today. Can we go ahead with the doc changes and get them live?

**Review by djw-m — APPROVED** [review]

**Pull request merged**
