### PR TITLE
Command line parameters for Windows and Mac

### PR DESCRIPTION
**Pull request by dwicinas**

### CODE REVIEW

**Comment by dwicinas** [comment]
@drothery-edb This is ready for your review. I'm not sure it needs a technical review. I used the information for PostgreSQL 15 that Nidhi provided and combined it with some of the definitions for PostgreSQL 10 found in the Wayback Machine. Nothing seems controversial. There are a couple parameter values that I don't define, but I would need some technical help to obtain those definitions. So I just left them undefined.

**Comment by drothery-edb** [comment]
Would it be possible to combine the two tables and just note the differences between platforms? Or does the scope of the differences between the two make that tricky?

**Comment by dwicinas** [comment]
There's two or three for windows that don't exist for Mac. And there's another 2-3 with different defaults. 
So it could be done in a single table, I think

**Comment by dwicinas** [comment]
@drothery-edb I consolidated the Mac and Windows descriptions. It's ready for your review, again.

**Review by drothery-edb — APPROVED** [review]

**Pull request merged**
