### PR TITLE
EPAS version 11 release notes

### PR DESCRIPTION
**Pull request by dwicinas**
## What Changed?

Point release information for EPAS version 11

### CODE REVIEW

**Comment by gsong** [comment]
⚠️ Rebased onto `develop`. @dwicinas If you have problems brining your local branch up to date, please reach out to @drothery-edb or @josh-heyer.

**Comment by drothery-edb** [comment]
rebased again. Dave, we will do it right this time.

**Comment by dwicinas** [comment]
I only gave this a light edit. @drothery-edb, you might want to give it a slightly more than cursory look.

In the release note for 11.1.7, I included Deprecated Features. Not sure whether that's correct.

**Review by drothery-edb — APPROVED** [review]
Made a couple of edits

**Pull request merged**
