### PR TITLE
Remove version-specific releases from Replication Manager documentation

### PR DESCRIPTION
**Pull request by gvasquezvargas**
## What Changed?

From slack conversation:

https://edb.slack.com/archives/CU5QEU5L7/p1721927285903279

I suggest we add a compatibility matrix so customers can know how to "mix and match" EPAS versions with EFM versions (what is supported and has been tested?).

### CODE REVIEW

**Comment by EFM-Bobby** [comment]
The changes look fine to me in terms of the sentences, but has anyone tested that other versions of pgpool work the same way?

**Comment by gvasquezvargas** [comment]
> The changes look fine to me in terms of the sentences, but has anyone tested that other versions of pgpool work the same way?

@EFM-Bobby I don't think anybody from our team has tested this so far, do you know if there is someone doing QA for connection poolers we could ask?

**Comment by EFM-Bobby** [comment]
> > The changes look fine to me in terms of the sentences, but has anyone tested that other versions of pgpool work the same way?
> 
> @EFM-Bobby I don't think anybody from our team has tested this so far, do you know if there is someone doing QA for connection poolers we could ask?

I don't know of anyone. That's essentially what I wrote in slack -- this change is an easy doc change, but I don't know if it's technically correct since I don't know of anyone testing things. As of today there's a movement to provide functionality in tpaexec to set this up, and once that works it would be easy to check the latest versions. I'll send a link to this PR to the people looking into it.

**Comment by EFM-Bobby** [comment]
Oh, the page about the VIP can be updated -- that's tested with every efm version. It's just the pgool/pgbouncer stuff that I don't know about.

**Comment by gvasquezvargas** [comment]
> Oh, the page about the VIP can be updated -- that's tested with every efm version. It's just the pgool/pgbouncer stuff that I don't know about.

@EFM-Bobby  gotcha, I can make the changes for pgbouncer and pgpool from a separate PR, then, until we know more. That way, we can merge and publish the changes for VIP now. 

What about client connect failover? If it has been tested, we can leave it in this PR and merge. If not, we can treat it as pgbouncer/pgpool and propose changes in a new PR until we know more.

**Comment by EFM-Bobby** [comment]
> 
> What about client connect failover? If it has been tested, we can leave it in this PR and merge. If not, we can treat it as pgbouncer/pgpool and propose changes in a new PR until we know more.

@gvasquezvargas Yes, sorry I missed that. You are correct -- we don't need any version info for that section. It's not actually an efm feature and so isn't tied to a version.

**Comment by gvasquezvargas** [comment]
Hey @EFM-Bobby ! I readded the pgpool/pgbouncer versions, just to be on the safe side. This PR is only removing the EPAS and EFM version-specific mentions. Could you please take a look and approve?

**Review by EFM-Bobby — APPROVED** [review]
Sure, looks good to me.

**Review by josh-heyer — APPROVED** [review]

**Pull request merged**
