### PR TITLE
More developed effort to templatize Linux install instructions for PostgreSQL

### PR DESCRIPTION
**Pull request by dwicinas**
## What Changed?

Fixes https://github.com/EnterpriseDB/docs/issues/3813

### CODE REVIEW

**Comment by dwicinas** [comment]
@drothery-edb This is a first crack and restructuring introductory information for PostgreSQL. Maybe you can take a look at what information I preserved and where I put it. I created an "Installation overview" topic, which may not be ideal but it seemed like a pretty easy way to capture some of the introductory information. Happy to take another approach, if you have ideas. Also, note that the Windows topic is still using graphics. I can remove those when we're ready.

**Comment by dwicinas** [comment]
@drothery-edb This PR is ready for your review and a technical review too.

**Comment by dwicinas** [comment]
@drothery-edb, I think this is ready for your review, again. It now incorporates the "check your repo" step, like the other products. I've also updated the Windows and Mac topics, including graphics, to reflect version 15.

**Comment by dwicinas** [comment]
@drothery-edb The changed files do include that package lock file. I'm not sure what to do about that.

**Comment by drothery-edb** [comment]
Before we merge this we should add the topics for RHEL 9 for versions 12-15.

**Review by drothery-edb — APPROVED** [review]

**Pull request merged**
