### PR TITLE
Implements Red Hat family templates for PostGIS

### PR DESCRIPTION
**Pull request by dwicinas**
Also implements some copy edits for PEM that must have been added to the templates in develop

Sets up template for PostGIS for:

RHEL 8 - x86
RHEL 7 - x86
Alma/Rocky 8 - x86
RHEL 8 - ppc

Also includes verbiage for install command for all PostGIS platforms

Also includes some copy edits for PEM that must have been added to the templates in develop

### CODE REVIEW

**Comment by dwicinas** [comment]
@nidhibhammar  @drothery-edb  There's one question for RHEL 7. The published documentation includes a big preliminary step. Is that still necessary? Other than that issue this might be good to be merged.

Are the changes to the install command what you had in mind, Dee Dee?

**Comment by drothery-edb** [comment]
We are going to have a version 3.1 and a version 3.2 of the PostGIS docs. I think we can leave the 3.1 topics as is (not generate or deploy them) and update the version number and deploy.mjs info so that we are just generating 3.2 topics. The 3.1 install command is different than the 3.2 commands. Ideally, we would have the templates set up to generate and deploy both versions correctly, but I'm not sure what the effort is for doing that. The 3.2 release hasn't been merged to develop yet so I think what we need to do is remove the generated topics from this branch, merge it, and then rebase the PostGIS 3.2 branch and update the deploy.mjs (and probably the config.yaml file) in the PostGIS 3.2 branch.

**Comment by drothery-edb** [comment]
Broken link: https://deploy-preview-2994--edb-docs-staging.netlify.app/docs/postgis/latest/01a_installing_postgis/installing_on_linux/x86_amd64/postgis_rhel8_x86/

**Review by nidhibhammar — APPROVED** [review]

**Comment by dwicinas** [comment]
@drothery-edb Here are the changes we discussed. I made wording for the install package consistent across all platforms based on the wording we were previously implementing for SLES and Ubuntu.

**Review by drothery-edb — APPROVED** [review]

**Pull request merged**
