### PR TITLE
MySQL FDW - install topics

### PR DESCRIPTION
**Pull request by nidhibhammar**
The install topics are generated but not deployed

This is the Debian/Ubuntu template work for the currently supported versions for MySQL.

### CODE REVIEW

**Review by dwicinas — DISMISSED** [review]
Looks good

**Comment by dwicinas** [comment]
@nidhibhammar @drothery-edb , I accidentally rebased this PR to develop. I thought I was working in a branch of my own. (Sorry!) The rebase encountered no issues, so I don't think I caused any problems. I just wanted you both to understand why you'll see some commits from me.

**Review by drothery-edb — CHANGES_REQUESTED** [review]
The links on the Installing on Linux and the x86 landing pages are broken in the deployment. Those need to be fixed before we merge this.

**Review by drothery-edb — APPROVED** [review]

**Comment by drothery-edb** [comment]
Just noticed that we are generating a Debian 11 topic. We shouldn't be doing that in this branch.

**Pull request merged**
