### PR TITLE
Switched in grey crosses for No

### PR DESCRIPTION
**Pull request by djw-m**
## What Changed?

Switched in grey crosses for no

### CODE REVIEW

**Comment by drothery-edb** [comment]
Just got an answer from Kelly. She prefers blanks to the x's.

**Comment by drothery-edb** [comment]
@djw-m I tried to switch back to using dashes for FALSE after Kelly landed on that approach being her preference, but it looks like my change generated an error.

**Comment by djw-m** [comment]
> @djw-m I tried to switch back to using dashes for FALSE after Kelly landed on that approach being her preference, but it looks like my change generated an error.

Looks like it rendered and deployed fine. What was the error you saw?

**Comment by drothery-edb** [comment]
> > @djw-m I tried to switch back to using dashes for FALSE after Kelly landed on that approach being her preference, but it looks like my change generated an error.
> 
> Looks like it rendered and deployed fine. What was the error you saw?

I must have been mistaken.

**Review by drothery-edb — APPROVED** [review]

**Comment by drothery-edb** [comment]
Kelly wants us to publish the changes PM has made tomorrow. I'll have her check the test deploy and if she approves will merge in the morning.

**Review by drothery-edb — APPROVED** [review]

**Pull request merged**
