### PR TITLE
Update 01_managing_barman_prerequisites.mdx

### PR DESCRIPTION
**Pull request by theadamwright**
Add link to the pg-barman-api page in the PEM "Prerequisites for managing Barman" page so that anyone doing an install doesn't have to go searching for the pg-barman-api docs. The link directs to the barman page with installation and securing instructions.

## What Changed?

Formatted code become a hyperlink 

## Checklist

**Content**

- [X ] This PR changes existing content

### CODE REVIEW

**Comment by drothery-edb** [comment]
@theadamwright, I think your change is fine, but I think we could simplify the topic as shown below. This includes a different link for Barman. I think we want to point to the community install instructions instead of our stub file. If you agree with these changes, @nidhibhammar or I can make them.
____________
Before adding a Barman server to the PEM console, install the following on the Barman host: 

- [Barman](https://docs.pgbarman.org/release/2.19/#installation).

- [Postgres backup API](https://www.enterprisedb.com/docs/supported-open-source/barman/pg-backup-api/).

**Comment by drothery-edb** [comment]
@theadamwright , @alwaite , I'm going to be doing a build today. I can get it into the build once you review it and let me know if you approve of my changes.

**Comment by theadamwright** [comment]
@drothery-edb I'm good with your suggested changes.

**Comment by alwaite** [comment]
I am good with the change, thanks.

**Pull request merged**
