### PR TITLE
Content/pem/8.2/upcoming release

### PR DESCRIPTION
**Pull request by nidhibhammar**
**DO NOT MERGE until PEM 8.2 is released** (tentative: [Sept. 14th](https://github.com/EnterpriseDB/docs/pull/1771#issuecomment-916262188))

## What Changed?

Changes for the PEM 8.2 upcoming release (supersedes #1723).

## Checklist

Please check all boxes that apply (`[ ]` is unchecked, `[x]` is checked)

**Content**

- [X] This PR adds new content
- [ ] This PR changes existing content
- [ ] This PR removes existing content

### CODE REVIEW

**Comment by nidhibhammar** [comment]
This is not ready to be merged with develop until 9th Sept.

**Review by drothery-edb — APPROVED** [review]

**Comment by nidhibhammar** [comment]
The release of PEM 8.2 is postponed (tentative date is 14th Sept). This is not ready to merge to develop branch until the release date.

**Comment by nidhibhammar** [comment]
@josh-heyer, @jericson-edb, need to run the build as PEM 8.2 release is going out today.

**Comment by nidhibhammar** [comment]
Also, we need to add the following tag:
product-pem-8.2.0

**Pull request merged**
