### PR TITLE
Update PDF chapter numbering algorithm and add tests

### PR DESCRIPTION
**Pull request by gsong**
### Tests for File Picking and Chapter Numbering

Add tests for file finding and chapter numbering:

- [x] No content index should not generate PDF
- [x] Root level index with content should generate PDF
- [x] No content index with subdirectories should have proper chapter numbers
- [x] Root index _and_ subdirectories should have proper chapter numbers

### Top-Level Peers to Non-Empty Index Are Chapter Numbered Properly

[Per discussion](https://github.com/EnterpriseDB/docs/issues/1290#issuecomment-861161063), top-level peers to non-empty `index.mdx` should get their own major chapter numbers.

I've staged updated files in [Google Drive](https://drive.google.com/drive/folders/1eLSeYFWlgr6IU6OedAXEFbqRoA8utr5S?usp=sharing).

### Generate Raw Text for PDF Diffs

In some cases, visual PDF diffs are hard to read (such as when there were outright missing chapters). `compare_pdfs.py` now has an optional `--text` flag which can be used to parse out raw text from the PDFs for comparison.

## Notes

If you would like to run the tests:

1. Create a Python 3.8+ virtual environment
2. `pip install -r requirements.txt`
3. `pytest`

For visual diffs of raw PDF text, I personally use the following tools:

* <https://www.perforce.com/products/helix-core-apps/merge-diff-tool-p4merge>
* <https://github.com/dandavison/delta>

### CODE REVIEW

**Comment by gsong** [comment]
@josh-heyer @jericson-edb @abhilasha-narendra @robert-stringer Did I miss any other combinations?

**Comment by gsong** [comment]
⚠️ Rebased.

**Review by jericson-edb — APPROVED** [review]
Great work! It's good we have the start of a test framework.

**Review by josh-heyer — APPROVED** [review]
Added one test case. Looks solid. Works like a charm!

**Comment by abhilasha-narendra** [comment]
This seems to be the perfect solution to our PDF issue. Thanks a lot @gsong

**Pull request merged**
