### PR TITLE
Fix broken internal link in BigAnimal docs

### PR DESCRIPTION
**Pull request by ringerc**
## What Changed?

Fixup for broken link in commit aa1117b0e

## Checklist

**Content**

- [ ] This PR adds new content
- [x] This PR changes existing content
- [ ] This PR removes existing content
- [ ] This PR is for a release, please add this tag:

### CODE REVIEW

**Comment by ringerc** [comment]
@drothery-edb I'm not sure if there's a better, more format-agnostic way to do internal links, but hope this is right.

Is it worth adding a basic style guide to the top level README, with hints about things like heading capitalisation, US-english spelling, internal links, etc?

**Review by drothery-edb — APPROVED** [review]
Thanks for fixing the link.

**Comment by drothery-edb** [comment]
@ringerc , good suggestion about linking to the style guide from the readme. I'll do that.

**Review by drothery-edb — CHANGES_REQUESTED** [review]
@ringerc , I just noticed that this PR has the change being merged into main. Please merge into develop instead.

**Review by josh-heyer — APPROVED** [review]

**Pull request merged**
