### PR TITLE
Add documentation for Postgres backup API

### PR DESCRIPTION
**Pull request by mikewallace1979**
Adds documentation for Postgres backup API (pg-backup-api) to the Barman
documentation.

## What Changed?

- Added page for Postgres backup API
- Added Installation page for Postgres backup API
- Added Securing Postgres backup API page

## Checklist

Please check all boxes that apply (`[ ]` is unchecked, `[x]` is checked)

**Content**

- [x] This PR adds new content
- [ ] This PR changes existing content
- [ ] This PR removes existing content
- [ ] This PR is for a release, please add this tag:

### CODE REVIEW

**Comment by drothery-edb** [comment]
Is this ready to be merged and to be published in the next production build?

**Comment by mikewallace1979** [comment]
@didiermichel thanks for the feedback - I tested the command lines for each target platform while putting the docs together though I wonder if I should do a final run through from the start

**Comment by mikewallace1979** [comment]
@drothery-edb we haven't finished the first release of pg-backup-api so I don't think this is ready to be merged and published just yet - shall I revert it to draft status?

**Comment by drothery-edb** [comment]
@mikewallace1979, keeping it in Draft until it is ready to merge is a good practice. Thanks.

**Comment by mikewallace1979** [comment]
> @mikewallace1979, keeping it in Draft until it is ready to merge is a good practice. Thanks.

Done - sorry I got carried away. Will mark this PR as ready when the packages are available.

**Comment by mikewallace1979** [comment]
@drothery-edb This is now ready for merging and deploying

**Review by drothery-edb — APPROVED** [review]

**Pull request merged**
