### PR TITLE
Restructure preqrequisites section for Linux install in PEM

### PR DESCRIPTION
**Pull request by dwicinas**
Changes to templates to move first two items into templatized content

Mostly wordsmithing and formatting on the remaining prerequisites page

### CODE REVIEW

**Comment by dwicinas** [comment]
@drothery-edb For your consideration... I didn't include Nidhi as a reviewer, but if you think she should review, that's fine with me. I don't think there's much that's noteworthy other then moving some chunks of information into the templatized structure.

**Comment by drothery-edb** [comment]
@nidhibhammar any concerns with this approach?

**Review by nidhibhammar — APPROVED** [review]
Looks good to me.

**Comment by drothery-edb** [comment]
@nidhibhammar I thought you were going to update one of the prerequisite bullets that you discovered wasn't correct?

**Comment by nidhibhammar** [comment]
@drothery-edb, yes I will be working on it in sometime.

**Review by drothery-edb — APPROVED** [review]

**Pull request merged**
