### PR TITLE
Update index.mdx

### PR DESCRIPTION
**Pull request by aswright491**
I would like to add 'Release Notes' to BigAnimal docs

### CODE REVIEW

**Comment by djw-m** [comment]
I just browsed this, and the release notes page is mostly dead links with no release notes and only one active note for over a year ago.

Do you know if more release notes are going to be added before this moves forward? And if so, shouldn't this PR be turned into a draft so the work can be completed?

**Comment by nidhibhammar** [comment]
@djw-m, I have just started working on this PR this morning as per the inputs from the BigAnimal team. More content is to be added, I am waiting for review comments.

**Comment by nidhibhammar** [comment]
@aswright491, should we publish the release notes?

**Review by nidhibhammar — APPROVED** [review]
LGTM

**Pull request merged**
