### PR TITLE
Docs/pem reorg

### PR DESCRIPTION
**Pull request by gsong**
Attempted fix of [pem_8_rel_consolidation](https://github.com/EnterpriseDB/docs/tree/pem_8_rel_consolidation) branch.

The changes that we care about:

```
R096    product_docs/docs/pem/7.16/index.mdx    product_docs/docs/pem/7/index.mdx
A       product_docs/docs/pem/7/pem_rel_notes/01_716_rel_notes.mdx
A       product_docs/docs/pem/7/pem_rel_notes/02_715_rel_notes.mdx
A       product_docs/docs/pem/7/pem_rel_notes/03_714_rel_notes.mdx
A       product_docs/docs/pem/7/pem_rel_notes/04_713_rel_notes.mdx
A       product_docs/docs/pem/7/pem_rel_notes/05_712_rel_notes.mdx
A       product_docs/docs/pem/7/pem_rel_notes/index.mdx
R098    product_docs/docs/pem/8.0/index.mdx     product_docs/docs/pem/8/index.mdx
R099    product_docs/docs/pem/8.1.0/pem_ent_feat/04_pem_erd_tool.mdx    product_docs/docs/pem/8/pem_ent_feat/04_pem_erd_tool.mdx
R096    product_docs/docs/pem/8.1.0/pem_ent_feat/17_monitoring_BDR_nodes.mdx    product_docs/docs/pem/8/pem_ent_feat/17_monitoring_BDR_nodes.mdx
R099    product_docs/docs/pem/8.1.0/pem_inst_guide_linux/04_installing_postgres_enterprise_manager/06_configuring_the_pem_server_to_use_kerberos_authentication.mdx     product_docs/docs/pem/8/pem_inst_guide_linux/04_installing_postgres_enterprise_manager/06_configuring_the_pem_server_to_use_kerberos_authentication.mdx
R076    product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/11_managing_database_objects/21_synonym_dialog.mdx       product_docs/docs/pem/8/pem_online_help/05_toc_pem_management_basics/11_managing_database_objects/23_synonym_dialog.mdx
A       product_docs/docs/pem/8/pem_rel_notes/08_810_rel_notes.mdx
A       product_docs/docs/pem/8/pem_rel_notes/09_801_rel_notes.mdx
A       product_docs/docs/pem/8/pem_rel_notes/10_800_rel_notes.mdx
A       product_docs/docs/pem/8/pem_rel_notes/index.mdx
```

* `R096` means the file was renamed and is 96% similar.
* `A` means the file was added.

I've omitted files that were deleted, and files that were renamed but is 100% the same. If you want to see a full list:

```sh
git diff --name-status develop
```

### CODE REVIEW

**Comment by gsong** [comment]
@drothery-edb @josh-heyer Can you please take a look at this to see if it's right?

**Comment by josh-heyer** [comment]
Recommend @drothery-edb check this out, build locally, and review to ensure that intended changes are still evident. Seems reasonable at a glance, but I'm not familiar enough with what was done previously on this branch to guarantee.

**Comment by drothery-edb** [comment]
@gsong, @josh-heyer the only thing we found when reviewing the files you listed above was with:
product_docs/docs/pem/8.0/pem_online_help/05_toc_pem_management_basics/11_managing_database_objects/21_synonym_dialog.mdx       product_docs/docs/pem/8/pem_online_help/05_toc_pem_management_basics/11_managing_database_objects/23_synonym_dialog.mdx

There were changes (removing the <figure> markup) that Nidhi made in the 8.0 version that should be in the 8 version. What is the best way to resolve that issue. Should Nidhi make the changes again in this branch?

**Comment by drothery-edb** [comment]
@gsong, @josh-heyer, @frago12,  I would like someone to look over my shoulder when I make my next set of commits to my branch. There are files showing up as changed that I want to make sure I should include in my commit. Thanks for all your help with this.

**Review by drothery-edb — APPROVED** [review]

**Pull request merged**
