### PR TITLE
Add description of bdr.queue.message_type values

### PR DESCRIPTION
**Pull request by nick-ivanov-edb**
## What Changed?

Added details to the description of the `bdr.queue.message_type` column.

## Checklist

Please check all boxes that apply (`[ ]` is unchecked, `[x]` is checked)

**Content**

- [ ] This PR adds new content
- [X] This PR changes existing content
- [ ] This PR removes existing content
- [ ] This PR is for a release, please add this tag:

### CODE REVIEW

**Comment by nick-ivanov-edb** [comment]
From here: https://github.com/EnterpriseDB/docs/pull/2804/commits

**Comment by drothery-edb** [comment]
Does this need a review or is it ready to be merged?

**Comment by nick-ivanov-edb** [comment]
I think it's benign; I just pulled the values from the source file.

**Review by drothery-edb — APPROVED** [review]

**Comment by drothery-edb** [comment]
I'll go ahead and merge then. Thanks.

**Pull request merged**
