### PR TITLE
build: tweak Dockerfile to work with preinstall

### PR DESCRIPTION
**Pull request by gsong**
Apparently `npm` behaves differently with the root user, which is what
the container runs as.

I wasn't able to build Docker images successfully as it was.

#### Dummy Icons

- [x] npm run docker:rebuild
- [x] npm start

#### Real Icons

- [x] npm run docker:rebuild
- [x] npm start

#### Dummy Icons

- [x] npm run docker:rebuild
- [x] npm start

#### Real Icons

- [x] npm run docker:rebuild
- [x] npm start

#### Dummy Icons

- [x] npm install
- [x] npm run develop

#### Real Icons

- [x] npm install
- [x] npm run develop

ℹ️ Pro tip: `docker system prune -f` after testing to clean up your Docker build cache and images.

### CODE REVIEW

**Comment by gsong** [comment]
⚠️ Rebased.

**Review by jaek-s — APPROVED** [review]
This looks good! Everything builds and runs correctly for me.

**Comment by gsong** [comment]
@jaek-s @frago12 ⚠️ Rebased, and added testing checklist.

**Review by jaek-s — APPROVED** [review]
I retested all of the cases in the description, and everything worked as expected.

**Pull request merged**
