### PR TITLE
Upgrade packages (Gatsby 3 & more)

### PR DESCRIPTION
**Pull request by epbarger**
## What Changed?
addresses https://github.com/EnterpriseDB/docs/issues/1056

- Upgrade to Gatsby 3, including related plugins. Biggest change under the covers is the update to Webpack v5, which means we may be seeing some deprecation messages for a bit.
- Upgrade Husky to v5, and migrate our husky install. Also configure a hook to automatically set husky up.
- Remove unneeded flags.
- Tweak icon script to remove a new eslint warning

Deprecation Warnings
- `DEP_WEBPACK_COMPILATION_ASSETS` and `DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK` should be fixed when `gatsby-plugin-netlify` releases version `3.2.0`
- `warn WebpackError: Unsafe builtin usage http.Agent` is from algoliasearch https://github.com/algolia/algoliasearch-client-javascript/issues/1261
- `warn Plugin gatsby-plugin-nginx-redirect is not compatible with your gatsby version 3.0.4 - It requires gatsby@^2.0.0` - seems to be working totally fine, opened issue to possibly update their peer dependency - https://github.com/gimoteco/gatsby-plugin-nginx-redirect/issues/6

## Checklist

Please check all boxes that apply (`[ ]` is unchecked, `[x]` is checked)

**Content**
- [ ] This PR adds new content
- [ ] This PR changes existing content
- [ ] This PR removes existing content

### CODE REVIEW

**Comment by gsong** [comment]
@epbarger I got a few of these warnings during `yarn build`, I assume they can be ignored?

```
warn Query takes too long:
File path: /Users/george/src/edb/docs/src/templates/doc.js
URL path: /pem/8.0/pem_ent_feat/04_performance_monitoring_and_management/
```

Other paths:

* URL path: /migration_portal/latest/04_mp_migrating_database/03_mp_schema_migration/
* URL path: /migration_portal/latest/04_mp_migrating_database/02_mp_schema_assessment/
* URL path: /epas/latest/epas_compat_reference/03_system_catalog_tables/
* URL path: /epas/latest/epas_compat_spl/

**Comment by gsong** [comment]
@epbarger 

I'm seeing this problem when running `yarn develop`. Am I doing something wrong?

https://user-images.githubusercontent.com/607420/111414782-d6ffae00-869d-11eb-972d-722434ff3d67.mp4

**Comment by epbarger** [comment]
@gsong Do you have a `dev-sources.json` file with stuff turned off? That would be my guess, especially if the full build is working fine.

**Comment by gsong** [comment]
@epbarger Yup, that was it. I needed to `yarn config-sources` and that did the trick.

**Review by gsong — APPROVED** [review]

**Comment by gsong** [comment]
@epbarger Successfully tested again with the latest updates.

**Pull request merged**
