### PR TITLE
Add missing column in `bdr.ddl_epoch`

### PR DESCRIPTION
**Pull request by nick-ivanov-edb**
Also fixed a typo in the description of `bdr.conflict_history.local_lsn`.

## What Changed?

- Add missing column in `bdr.ddl_epoch`
- Fix a typo in the description of `bdr.conflict_history.local_lsn`

## Checklist

Please check all boxes that apply (`[ ]` is unchecked, `[x]` is checked)

**Content**

- [ ] This PR adds new content
- [X] This PR changes existing content
- [ ] This PR removes existing content
- [ ] This PR is for a release, please add this tag:

### CODE REVIEW

**Review by drothery-edb — APPROVED** [review]
Do you want someone else to review this or is it ready to merge?

**Comment by nick-ivanov-edb** [comment]
> Do you want someone else to review this or is it ready to merge?

May be @pavanvd - he was the original developer?

**Comment by drothery-edb** [comment]
@pavanvd can you review this, please? We are in the process of moving source files and I need to do some branch maintenance. How I do the cleanup is dependent on how long the PR might be open.

**Comment by drothery-edb** [comment]
@nick-ivanov-edb , before this can be merged the changes need to be implemented in the new location where the BDR files now reside: product_docs/docs/pgd/4/overview/bdr/catalogs.mdx.

**Comment by djw-m** [comment]
Closing as done elsewhere.

**Pull request closed without merging**
