### PR TITLE
Revert "Update index.mdx"

### PR DESCRIPTION
**Pull request by jpe442**
Reverts EnterpriseDB/docs#5410

### CODE REVIEW

**Review by josh-heyer — APPROVED** [review]
Don't forget to create a new PR that reverts this PR... 😁

**Comment by jpe442** [comment]
> Don't forget to create a new PR that reverts this PR... 😁

You are joking right 🤞 😓 ?

**Comment by jpe442** [comment]
Not you aren't joking. I just thought through it and I will need another PR reversion to get this back won't I?

**Comment by josh-heyer** [comment]
Yep...!

**Pull request merged**
