### PR TITLE
EPAS 15 - Updated, modifying the data directory location as per DB-2501

### PR DESCRIPTION
**Pull request by nidhibhammar**

### CODE REVIEW

**Comment by tusharahuja** [comment]
Thanks, please change path /tmp/as15 to some proper path like /var/data, the rest looks good.

**Comment by tusharahuja** [comment]
looks good.

**Review by tusharahuja — APPROVED** [review]
looks good.

**Review by tusharahuja — APPROVED** [review]
looks good.

**Review by tusharahuja — APPROVED** [review]

**Review by ccestes — APPROVED** [review]

**Pull request merged**
