### PR TITLE
Update 01_cluster_networking.mdx

### PR DESCRIPTION
**Pull request by ftouserkani-edb**
## What Changed?

Please list, at a high level, what changed in your branch. If you changed content, include the product, section, and version as applicable. **Please remove the user instructions including the examples before merging the PR.**

**Examples**

- Fixed typo in EPAS 13 epas_inst_linux guide
- Added more detail to ARK 3.5 getting started guide introduction
- Fixed broken link on `/supported-open-source/pgbackrest/05-retention_policy/` page

## Checklist

Please check all boxes that apply (`[ ]` is unchecked, `[x]` is checked)

**Content**

- [ ] This PR adds new content
- [ ] This PR changes existing content
- [ ] This PR removes existing content
- [ ] This PR is for a release, please add this tag:

### CODE REVIEW

**Comment by ftouserkani-edb** [comment]
Fixed typo in CIDR block address.

**Comment by drothery-edb** [comment]
Thanks for fixing the typo, @ftouserkani-edb. We really appreciate it when folks take the time to help us improve the documentation. I have asked the writer who worked on this topic and the developer to confirm the change and to check if it needs to be made anywhere else then we will merge it. Thanks again.

**Review by moiznalwalla — APPROVED** [review]
This looks like a typo that crept in while transferring text from google doc to mdx.

**Comment by moiznalwalla** [comment]
Will quickly parse through the doc to check if similar corrections are required.

**Pull request merged**
