### PR TITLE
BigAnimal: BYOA vs BAH roadmap

### PR DESCRIPTION
**Pull request by ccestes**
## What Changed?

Prototype of Deployment options restructure, which includes a parent topic and child topics with csp roadmaps 

Based on this [spreadsheet](https://docs.google.com/spreadsheets/d/1F7hTV4CsH17gtTBbuP5pQF5zVXG0oxa-wg5mUvL-xPs/edit#gid=0)

Link to the draft: https://deploy-preview-4322--edb-docs-staging.netlify.app/docs/biganimal/latest/deployment_options/

### CODE REVIEW

**Comment by josh-heyer** [comment]
@ccestes can you provide a status update / expected date for this, and make sure someone else on the docs team has access to the spreadsheet?

**Comment by ccestes** [comment]
@josh-heyer This was an idea of Dee Dee's to provide users with a roadmap/list of pages for each deployment type. You can see that we added child topics in [Deployment options](https://deploy-preview-4322--edb-docs-staging.netlify.app/docs/biganimal/latest/planning/deployment_options/). Last I heard, Jason was going to take a look at this PR which was intended as a prototype but wasn't ready to be published. Possibly they were waiting to restructure the BA docs. 

I'll share the spreadsheet with you and Nidhi.

**Review by amrita-suresh — APPROVED** [review]

**Comment by dwicinas** [comment]
@amrita-suresh You approved these changes several months ago, but somehow this PR got lost in the shuffle when Dee Dee left. Now I'm trying to close the loop. If you care, you might want to take another look at the changes. The only thing I've done since your last review way back when is to clean up some broken or misdirected links.

**Comment by amrita-suresh** [comment]
this looks good to me @dwicinas! thanks

**Pull request merged**
