### PR TITLE
Update 06_monitoring_efm_cluster.mdx

### PR DESCRIPTION
**Pull request by matthew123987**
## What Changed?

added how to check real-time replication status.

### CODE REVIEW

**Comment by matthew123987** [comment]
@EFM-Bobby please may I have a review

**Review by EFM-Bobby — APPROVED** [review]
It's ok with me. Someone might wonder how they're supposed to use efm to run that, so you might want more info like "To get... connect to the primary database and execute the command ...." along with a link to postgres docs. But if the existing test is ok with anyone on doc team it's ok with me.

**Comment by EFM-Bobby** [comment]
Sure, I think that's more clear. It SHOULD have been obvious the way you had it but you never know....

**Review by EFM-Bobby — DISMISSED** [review]

**Comment by matthew123987** [comment]
Thank you!

**Comment by matthew123987** [comment]
@drothery-edb would you like to review this, or shall I merge?

**Review by drothery-edb — APPROVED** [review]

**Comment by matthew123987** [comment]
> no need for please

I like your style :D

**Pull request merged**
