### PR TITLE
update dependencies: September 2023

### PR DESCRIPTION
**Pull request by josh-heyer**
## What Changed?

Notable updates:

- Husky
- Prettier
- Algolia 
- Bootstrap

The last two required substantial revisions to support the major version updates. As part of these, I've fixed a few related issues:
- incorrect path parsing for 404 page search (it was prefixing most searches with "docs")
- race condition in global search bar initialization (click too fast, no search)
- honor system dark mode preference when no local preference is set

Also replaced pretty-quick with lint-staged, as new prettier is unsupported by the former. May not have the configuration quite right for this.

### CODE REVIEW

**Comment by djw-m** [comment]
The search box's category -> All Products etc. -> has flipped from white on blue to black on blue.

**Comment by djw-m** [comment]
image

Little odd - I assume that it's the mismatch between the algolia db and the preview but wanted to flag that.

**Review by djw-m — DISMISSED** [review]
Apart from the color change in the search box,LGTM. Couldn't snag anything else.

**Comment by josh-heyer** [comment]
Took me way too long to figure out the color thing. Turns out Boostrap 5 picks a foreground color based on what will provide the best contrast for the background... And our blue has crappy contrast with white:

image

Options: 

1. Leave text black (and adjust styles on other buttons to match)
2. Use a slightly darker shade of blue (e.g. `#3e6e8e`)

**Comment by djw-m** [comment]
I would likely go for a darker shade of blue and the black/blue contrast is
more painful.

**Comment by josh-heyer** [comment]
Altered rules to achieve consistency for now; added #4868 to track future work on better contrast.

**Pull request merged**
