### PR TITLE
EDB PgBouncer 1.23 release

### PR DESCRIPTION
**Pull request by gvasquezvargas**
## What Changed?

New upstream merge of PgBouncer https://enterprisedb.atlassian.net/browse/RL-177 
Also edited the 1.16.1.0 topic title, as it said 1.16.0.0 when referring to a 1.16.1.0 release.

### CODE REVIEW

**Review by nidhibhammar — APPROVED** [review]
LGTM

**Review by ajit-at-edb — APPROVED** [review]
Looks good.

**Comment by ajit-at-edb** [comment]
Please add @tusharahuja  as reviewer for this PR.

**Review by tusharahuja — APPROVED** [review]
looks good.

**Pull request merged**
