### PR TITLE
First draft of documentation changes for efm 4.7

### PR DESCRIPTION
**Pull request by EFM-Bobby**
## What Changed?

Version changes through user's guide.

Added 4.7 release notes page.

### CODE REVIEW

**Review by kelpoole — APPROVED** [review]
I've looked through the changes and the release notes. I'm assuming there's no inline content where the enhancement change should be discussed.

**Review by kelpoole — APPROVED** [review]
I've looked through the changes and the release notes. I'm assuming there's no inline content where the enhancement change should be discussed.

**Comment by EFM-Bobby** [comment]
> I've looked through the changes and the release notes. I'm assuming there's no inline content where the enhancement change should be discussed.

Good thinking, and correct. The guide only mentions that we create a backup when a standby is reconfigured and that the user can remove it, which is still the case.

**Comment by EFM-Bobby** [comment]
Hi @drothery-edb, can you give this a look when you get a chance? I don't know when the packages will actually be released, so we shouldn't merge these changes yet, but would like to do everything we can ahead of time.

**Comment by EFM-Bobby** [comment]
Update for whomever -- I changed the 4.7 release date in the doc to tomorrow, May 25, just to pick *something*. Am happy to change it as needed.

**Comment by drothery-edb** [comment]
@EFM-Bobby , the individual install topics are generated from a template. Any changes needed to those topics should be done in the templates and the files regenerated. You can see the change I made to the templates [here](https://github.com/EnterpriseDB/docs/pull/4023/commits/63067a1eb9dacf6557119f5d73620140f8d55fb3). You are welcome to familiarize yourself with our template framework or we can make those changes for you in the future.

**Review by drothery-edb — DISMISSED** [review]

**Review by drothery-edb — DISMISSED** [review]

**Pull request merged**
