### PR TITLE
Update efm4_rhel_8_x86.mdx

### PR DESCRIPTION
**Pull request by martinmarques**
The less and greater symbols may confuse the user, and they actually need to change the `USERNAME:PASSWORD` part.

## What Changed?

Remove the `<` and `>` which were incorrect and might lead to confusion.

## Checklist

Please check all boxes that apply (`[ ]` is unchecked, `[x]` is checked)

**Content**

- [ ] This PR adds new content
- [ x ] This PR changes existing content
- [ ] This PR removes existing content
- [ ] This PR is for a release, please add this tag:

### CODE REVIEW

**Comment by martinmarques** [comment]
@drothery-edb I see this same pattern in other pages of the EFM docs (namely all the installations that branch from [this section](https://www.enterprisedb.com/docs/efm/latest/03_installing_efm/x86_amd64/). Any chance we can replicate the simple patch on the other sections if @EFM-Bobby agrees :-)

**Comment by EFM-Bobby** [comment]
To me your change implies that they need to change <username>:<password> to <somename>:<somepassword> and keep the <> symbols.

**Comment by martinmarques** [comment]
The code snippet is this:

```
#  Replace '<USERNAME>' and '<PASSWORD>' below with
#  your username and password for the EDB repository:
sed -i "s@<username>:<password>@USERNAME:PASSWORD@" /etc/yum.repos.d/edb.repo
```

That will replace occurrences of `<username>` with `USERNAME` and occurrences of `<password>` with `PASSWORD`. That's why we should remove the `<` and `<` from the comment in the code.

**Comment by martinmarques** [comment]
One thing to note is that this change doesn't affect Ubuntu and Debian installation instructions as in those it's correctly commented with respect to the code that installs the repository

**Comment by EFM-Bobby** [comment]
> The code snippet is this:
> 
> ```
> #  Replace '<USERNAME>' and '<PASSWORD>' below with
> #  your username and password for the EDB repository:
> sed -i "s@<username>:<password>@USERNAME:PASSWORD@" /etc/yum.repos.d/edb.repo
> ```
> 
> That will replace occurrences of `<username>` with `USERNAME` and occurrences of `<password>` with `PASSWORD`. That's why we should remove the `<` and `<` from the comment in the code.

But we want "<username>" replaced with the name and not just "username" replaced with the name don't we? Or do we want the <>s in the line after the replacement? I have not used these instructions and don't understand what the problem is.

**Comment by EFM-Bobby** [comment]
> > The code snippet is this:
> > ```
> > #  Replace '<USERNAME>' and '<PASSWORD>' below with
> > #  your username and password for the EDB repository:
> > sed -i "s@<username>:<password>@USERNAME:PASSWORD@" /etc/yum.repos.d/edb.repo
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That will replace occurrences of `<username>` with `USERNAME` and occurrences of `<password>` with `PASSWORD`. That's why we should remove the `<` and `<` from the comment in the code.
> 
> But we want "" replaced with the name and not just "username" replaced with the name don't we? Or do we want the <>s in the line after the replacement? I have not used these instructions and don't understand what the problem is.

certainly USERNAME->username ought to be fixed though

**Review by EFM-Bobby — APPROVED** [review]
Yes, I'm ok with this once I finally saw what was going on. Like written elsewhere, this change should probably be in a lot of places.

**Comment by martinmarques** [comment]
Added changes to the RHEL7 and Centos7 files which required the same fix in the docs

**Comment by martinmarques** [comment]
I think I got all changes in now.

**Review by EFM-Bobby — APPROVED** [review]
Looks good.

**Comment by EFM-Bobby** [comment]
(Removed my other comments when I wasn't understanding which words were being replaced -- the latter instances of username/password -- so it doesn't cause even more confusion.)

**Comment by drothery-edb** [comment]
These are very good comments but as discussed in Slack, we will be closing this PR because these topics are generated. We will add a comment to that effect in the generated topics going forward. Since we are very close to updating these topics to not include the repo instructions, we aren't planning to make this temporary improvement as the change would affect many topics (all RHEL family install topics for all the EDB heritage products) and the testing effort isn't quite justified.

**Pull request closed without merging**
