### PR TITLE
updating doc-release-tag-format table

### PR DESCRIPTION
**Pull request by drothery-edb**
Adding column for PMs, POs, and any other interested parties who want to be informed about updates to their product docs.
The plan is for PR owners to include the interested parties as reviewers, as appropriate.

### CODE REVIEW

**Comment by drothery-edb** [comment]
@kelpoole , can you check that I added the correct PMs and POs? Thanks.

**Comment by drothery-edb** [comment]
@jericson , this PR has been lingering for a while. Does this address the feedback you received?

**Review by jericson-edb — APPROVED** [review]
Looks good to me!

**Comment by drothery-edb** [comment]
@jericson-edb , do you mind reviewing again? Do you think it is appropriate to add a link to the style guide from the readme?

**Comment by jericson-edb** [comment]
>  Do you think it is appropriate to add a link to the style guide from the readme?

It would be better if we had a public style guide. For the moment we don't have a lot of outside contributors, but it would be annoying to people who want to help , but can't be sure they are submitting changes we will approve. Probably better to have the link than not, however.

**Pull request merged**
