### PR TITLE
standardized URLs for p-products

### PR DESCRIPTION
**Pull request by dwicinas**
Reworked installing directory, including all install topics, to implement consistent approach to file naming to result in standardized URLs

### CODE REVIEW

**Comment by dwicinas** [comment]
@drothery-edb I think this PR is ready to be merged. However, I did do some rewriting and reorganizing to more cleanly split pgpool from pgpool extensions. You might want to review what I did. Reading those changed topics closely reveals some rugged language. For sections that I touched, I tried to smooth out the language, but there's a few other questionable sections in the areas that I did not touch.

**Comment by dwicinas** [comment]
Note that I did insert "latest" into all the manually created redirect paths. I left the system-generated paths alone.

**Review by drothery-edb — CHANGES_REQUESTED** [review]
@dwicinas please run the link checker and fix any broken links. I believe we have some in pgpool. Thanks.

**Comment by dwicinas** [comment]
@drothery-edb I fixed the broken links for pgpool, which required a fix to one of the template files. I also modified the base template file for MTK, which was generating broken links in all the MTK files. That base template file now also correctly updates redirects in all the generated MTK topics.

**Review by drothery-edb — APPROVED** [review]

**Pull request merged**
