### PR TITLE
Remove beta logo

### PR DESCRIPTION
**Pull request by frago12**

### CODE REVIEW

**Comment by frago12** [comment]
@josh-heyer the interactive demo on the homepage is showing the logo with the beta flag, do we want to redo it?

image

**Comment by josh-heyer** [comment]
We should probably swap that out - it's been up for a while now. Any suggestions on a new topic to feature there, @drothery-edb ?

**Comment by drothery-edb** [comment]
@josh-heyer , are you asking about the banner at the top of every page that says: This is the redesigned EDB Docs site. For older product docs, go to the EDB Docs Archive? Can we remove the banner altogether and just use it with updated text when needed?

**Comment by josh-heyer** [comment]
No, the "featured topic" banner on the homepage - that's where the animation above lives.

**Comment by josh-heyer** [comment]
Merge when comfortable, @frago12 !

**Pull request merged**
