### PR TITLE
chore(UPM-10477): Adding new BDR metrics to documentation

### PR DESCRIPTION
**Pull request by gbulloch-edb**
## What Changed?

Added new BDR metrics to existing metrics documentation located here:
/docs/product_docs/docs/biganimal/release/using_cluster/05_monitoring_and_logging/metrics/index.mdx

This was generated with the script written by @ringerc which I've also now commited to our scripts repo here:
https://github.com/EnterpriseDB/starlight-scripts/blob/main/docs/metrics_to_markdown_txt.py

## Checklist

Please check all boxes that apply (`[ ]` is unchecked, `[x]` is checked)

**Content**

- [ ] This PR adds new content
- [x] This PR changes existing content
- [ ] This PR removes existing content
- [ ] This PR is for a release, please add this tag:

### CODE REVIEW

**Comment by gbulloch-edb** [comment]
Looks like description fields against each metric did not get generated by the script this time, added do-not-merge tag for now so this can be investigated, suspect these might have been added manually

**Review by matthewhudsonedb — DISMISSED** [review]
LGTM

**Comment by drothery-edb** [comment]
Optional formatting recommendations that may improve usability by taking advantage of right nav pane and more clearly representing the metrics and label tables as applying to the metric group:

- Change the metric group headings to head 2s (##)
- Remove “Group” from the title. I don’t think it is necessary and would keep the title from wrapping on the right nav.
- Remove the Metrics and Labels headings. I don’t think they are necessary and then you can remove “above” from the labels description.

This is example output if you make these changes:
image

**Review by drothery-edb — DISMISSED** [review]
Let me know if you want me to apply the optional formatting suggestions I made.

**Review by drothery-edb — APPROVED** [review]

**Pull request merged**
