### PR TITLE
Add description of `bdr.queue.message_type` values

### PR DESCRIPTION
**Pull request by nick-ivanov-edb**
## What Changed?

Added descriptions of possible values in the `message_type` column of `bdr.queue`, lifted from `pglogical_queue.h`.

## Checklist

**Content**

- [ ] This PR adds new content
- [X] This PR changes existing content
- [ ] This PR removes existing content
- [ ] This PR is for a release, please add this tag:

### CODE REVIEW

**Comment by drothery-edb** [comment]
@nick-ivanov-edb does this change need to be reviewed or is it ready to be merged? I'm doing some branch maintenance because we are in the process of moving the source files. Depending on the status of this branch I will either move the change to the source files in the new location in a new branch or I'll implement the change in the branch associated with https://github.com/EnterpriseDB/docs/pull/2971. Let me know if it needs to be reviewed first or if it is ready for me to merge. Thanks.

**Comment by drothery-edb** [comment]
@nick-ivanov-edb , before this can be merged the changes need to be implemented in the new location where the BDR files now reside: product_docs/docs/pgd/4/overview/bdr/catalogs.mdx

**Comment by nick-ivanov-edb** [comment]
@drothery-edb I apologise for not responding earlier, I was away. If it's not too late I'd like to implement the changes, but I have trouble locating "product_docs/docs/pgd/4/overview/bdr/catalogs.mdx" -- what site is that on?

**Comment by drothery-edb** [comment]
My apologies, @nick-ivanov-edb, I should have given you the full path: https://github.com/EnterpriseDB/docs/blob/develop/product_docs/docs/pgd/4/overview/bdr/catalogs.mdx

**Comment by djw-m** [comment]
On checking, this PR has been manually implemented (and fixed) in BDR 4 and PGD 5 docs. No action is required.

**Pull request closed without merging**
