### PR TITLE
BDR-3803 - PGD CLI 5.2.0 doc changes

### PR DESCRIPTION
**Pull request by Jagdish-Kewat-EDB**
Update command help doc for verify-settings

Do not merge until PGD 5.2.0 is released.

Ref: BDR-3803

### CODE REVIEW

**Review by djw-m — APPROVED** [review]
No you have added so much example text, the actual options (minimal though they are) are now many pages away for the average reader. Luckily, the right hand nav saves the day but I'd like to flag this layout for review and reader optimization.

**Comment by Jagdish-Kewat-EDB** [comment]
> No you have added so much example text, the actual options (minimal though they are) are now many pages away for the average reader. Luckily, the right hand nav saves the day but I'd like to flag this layout for review and reader optimization.

It is a auto-generated page. It provides help for the command with sample output. And the other flags/options are generic options for all commands

**Comment by djw-m** [comment]
Then this is definitely going into the for review for reworking pile.

**Comment by djw-m** [comment]
Merged through restaging52

**Pull request closed without merging**
