### PR TITLE
Deprecating EDB Docs 1.0

### PR DESCRIPTION
**Pull request by robert-stringer**
## What Changed?

Work in progress

## Checklist

Please check all boxes that apply (`[ ]` is unchecked, `[x]` is checked)

**Content**
- [ ] This PR adds new content
- [ ] This PR changes existing content
- [ ] This PR removes existing content

### CODE REVIEW

**Review by gsong — DISMISSED** [review]

**Comment by gsong** [comment]
@frago12 👍

**Comment by frago12** [comment]
@robert-stringer just updated the `<Archive />` component to point to the [archive docs repo](https://github.com/EnterpriseDB/docs-archive), let me know if this looks good to you

**Comment by drothery-edb** [comment]
Can we close this PR now?

**Comment by robert-stringer** [comment]
Yes, please close.

**Pull request closed without merging**
