### PR TITLE
Change name of powertools to crb for Rocky and Alma Linux 9

### PR DESCRIPTION
**Pull request by dwicinas**
Changes the command for enabling powertools from "powertools" to "crb" for all products installed on Rocky or Alma Linux 9.

This PR also picks up a change to EPAS that must have been made in the templates but never propagated to all the versions of EPAS. I'm including it in this PR so all the templatized output is consistent.

This PR responds to [PR-5197](https://github.com/EnterpriseDB/docs/pull/5197) but I don't have access to that branch.

### CODE REVIEW

**Comment by dwicinas** [comment]
@nidhibhammar Please take a look at the files changed in this PR. The change for Rocky/Alma Linux 9 seems pretty straightforward, but it seems like we must have made a change to the templates for EPAS post-install configuration that we didn't propagate to all the various versions of EPAS. I'm including those changes here to keep the generated install files in sync with the templates. If you don't like that, I can work to separate out the Rocky/Alma Linux 9 change from the EPAS change and we can put them into two separate PRs. Adding @djw-m  because he seems to have a handle on the Rocky/Alma change.

**Review by djw-m — APPROVED** [review]
Reviewing the output, LGTM.

**Comment by nidhibhammar** [comment]
@dwicinas, everything looks good except the one change you pointed out for EPAS. Let's fix that before moving ahead if it is not too much time-consuming.

**Comment by nidhibhammar** [comment]
@dwicinas, yes, I meant to fix the psql output change. It should reflect the exact version it is. Previously it was 15.2.0 for all versions, of which we are unaware. Now that we know, let's fix it, and the psql output should show the exact version it is in. 
for eg: version 12 should show psql 12.x.0.

**Pull request merged**
