### PR TITLE
bdr_pg_upgrade product doc update

### PR DESCRIPTION
**Pull request by smaher-edb**
## What Changed?
- Removed the pre-upgrade step (which alters the conn limit to 0 at db level) message, as this step is being removed from the actual code.
- Add supported version for BDR 3.7

Ref: BDR-4159

Note: This PR can be merged only at the time of `PGD v5.3` release, tentatively scheduled for `14th Nov 2023`.

### CODE REVIEW

**Review by djw-m — APPROVED** [review]
LGTM

**Comment by smaher-edb** [comment]
Have pushed 1 more change which was added in upcoming release - support for BDR 3.7.22 and above.

**Comment by smaher-edb** [comment]
@PJMODOS adding you to the reviewer for minor addition related to v3.7.22+.

**Review by djw-m — COMMENTED** [review]
The sentence has become somewhat complex. I would suggest separating the requirement for same version from the supported versions for clarity.

* The same BDR version must be running on both clusters.
* The BDR version must be 4.1.0 or above. Version 3.7.22 and later is also supported.

**Comment by smaher-edb** [comment]
> The sentence has become somewhat complex. I would suggest separating the requirement for same version from the supported versions for clarity.
> 
>     * The same BDR version must be running on both clusters.
> 
>     * The BDR version must be 4.1.0 or above. Version 3.7.22 and later is also supported.

Ok fixed. Just replaced `running` with `installed` as new cluster must not be in running mode (to avoid any confusion).

**Review by djw-m — APPROVED** [review]
LGTM

**Pull request merged**
