### PR TITLE
EPRS - 7.7.0 Release branch

### PR DESCRIPTION
**Pull request by nidhibhammar**
## What Changed?

Updated windows installation pre-requisites as per XDB-2164

### CODE REVIEW

**Comment by dwicinas** [comment]
@nidhibhammar I wasn't sure whether XDB-2180 was saying that we needed to create release notes for version 7.7 Just in case, I added release notes in my one commit (23b75c4(. If that was unnecessary I can revert that commit.

**Comment by nidhibhammar** [comment]
Thank you @dwicinas for your help on this.

**Review by anwar-sahib — APPROVED** [review]
All the changes for 7.7.0 release look good.

**Review by anwar-sahib — APPROVED** [review]

**Review by djw-m — APPROVED** [review]
LGTM

**Pull request merged**
